### ISSUE TITLE
Create a CLI argument for outputting results to a file

### ISSUE THREAD

**Issue by ndelvalle** [ndelvalle/nakatoshi#17]
This item was previously in the TODO section in the readme. This sections was removed so I migrate it to an issue.
CC @mrfu2

**Comment by whizsid** [comment]
I would like to work on this feature. My approach is to make a macro to write to file ( Replacing `println` with a macro). Are we want to hide the CLI output when writing to the file?

**Comment by mrfu2** [comment]
Looking at an example application such as https://github.com/samr7/vanitygen (C++), this application logs to file AND prints output. So the user gets some visual feedback about the workings of the application. This allows the user to adjust the phrases when needed. Because a short phrase will output >1000 results per minute whereas a long phrase won't produce any output in the next 2 years.

Whether or not nakatoshi prints results as they are found, I do advise in showing the user at least some information regarding found results, for example giving a statistic like "{num_found} addresses found in {run_time}" which would look like "24 addresses found in 5 minutes".

**Comment by ndelvalle** [comment]
@whizsid that is great! 🙌🏻
I am not familiar with writing macros yet, so I'll live that choice to you, to implement it the best way you see fit.
I would say that if the feature support only 1 result IMO lets just output the result in the file, if the feature will support writing multiple addresses to the file (https://github.com/ndelvalle/nakatoshi/issues/18) It would be nice to have a bit of feedback like mrfu2 suggested.
